name: Setup workspace
description: Configure toolchain and install workspace dependencies

runs:
  using: composite
  steps:
    - uses: voidzero-dev/setup-vp@v1.21.1
      with:
        node-version: "26.10.0"
        cache: true
        run-install: |
          args: ["--frozen-lockfile"]
