packages:
  - packages/*
  - apps/*

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bufferutil: true
  core-js: true
  esbuild: true
  netlify-cli: true
  sharp: true
  unix-dgram: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - '@swc/core-darwin-arm64@1.16.2'
  - '@swc/core-darwin-x64@1.16.2'
  - '@swc/core-linux-arm-gnueabihf@1.16.2'
  - '@swc/core-linux-arm64-gnu@1.16.2'
  - '@swc/core-linux-arm64-musl@1.16.2'
  - '@swc/core-linux-ppc64-gnu@1.16.2'
  - '@swc/core-linux-s390x-gnu@1.16.2'
  - '@swc/core-linux-x64-gnu@1.16.2'
  - '@swc/core-linux-x64-musl@1.16.2'
  - '@swc/core-win32-arm64-msvc@1.16.2'
  - '@swc/core-win32-ia32-msvc@1.16.2'
  - '@swc/core-win32-x64-msvc@1.16.2'
  - '@swc/core@1.16.2'
  - netlify-cli@27.5.0
