packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram
  - utf-8-validate
