import { createRequire } from "node:module"
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// Generated by `pnpm lib:build-docs` (TypeDoc + typedoc-docusaurus-theme).
const typedocItems = createRequire(import.meta.url)(
  "./generated-api/typedoc-sidebar.cjs"
) as Extract<SidebarsConfig[string], unknown[]>

const sidebars: SidebarsConfig = {
  api: [
    { type: "link", label: "← Back to the docs", href: "/intro" },
    { type: "html", value: "API reference", className: "sidebar-section-label" },
    { type: "doc", id: "index", label: "Overview" },
    ...typedocItems,
  ],
}

// biome-ignore lint/style/noDefaultExport: Docusaurus loads sidebars via a default export.
export default sidebars
